name: Maintenance

on:
  - workflow_dispatch

jobs:

  cgitize:
    secrets: inherit
    uses: ./.github/workflows/cgitize.yml

  infra:
    secrets: inherit
    uses: ./.github/workflows/infra.yml

  jekyll:
    secrets: inherit
    uses: ./.github/workflows/jekyll.yml

  yandex-cloud-cli-bin:
    secrets: inherit
    uses: ./.github/workflows/yandex-cloud-cli-bin.yml
